[project]
name = "advanced-rag"
version = "0.1.0"
description = "Content for Mastering LLM with Advanced RAG online course."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "ruff>=0.6.7",
]
